#!/bin/bash

# url="127.0.0.1:8000"
tempfile='old-result.md5'

usage() {
	echo -e "Usage: $0 [options] url\n"
	echo "Options:"
	echo "  -i interval  set the interval of checks"
	echo "  -n           send Desktop notifications"
	echo "  -h           Show this help message"
	exit 1
}


while getopts ":hni:" opt; do
	case ${opt} in
		h )
			usage
			;;
		i )
			interval=$OPTARG
			;;
		n ) 
			notify=true
			;;
		\? )
			usage
			;;
		: )
			usage
			;;
	esac
done

shift $((OPTIND -1))

if [[ -z "$1" ]]; then
	echo -e "Error: No url given\n"
	usage
	exit 1
else
	url=$1
fi 

if [[ -z $interval ]]; then
	interval=30
fi

checkchange() {
	result=$(curl -L -s --insecure $url | md5sum --zero | sed "s/  -//g" 2>/dev/null)
	
	if [[ ! -f "$tempfile" ]]; then
		touch $tempfile
		echo "$result" > $tempfile
	elif [[ "$result" == "$(cat $tempfile)" ]]; then
		checkresult="$url Hasn't changed"
		changed=false
	elif [[ "$result" != $(echo $tempfile) ]]; then
		checkresult="$url Has changed"
		changed=true
		echo $result > $tempfile
	fi

	echo -e "$checkresult\n"
	
	if [[ $notify ]]; then
		if [[ $changed == true ]]; then
			notify-send -u critical bash-web-monitor "\n$checkresult"
		elif [[ $changed == false ]]; then
			notify-send -u low -t 2000 bash-web-monitor "\n$checkresult"
		fi
	fi

	sleep $interval
}

close() {
	echo "removing temporary file"
	rm $tempfile
	exit 0
}

trap close SIGINT SIGTERM

while true; do
	checkchange
done