#!/bin/bash

url="moed.gov.sy"
tempfile='old-result.md5'

while [ true ]; do
	
	result=$(curl -L -s --insecure $url | md5sum --zero | sed "s/  -//g" 2>/dev/null)
	
	if [[ ! -f "$tempfile" ]]; then
		touch $tempfile
		echo "$result" > $tempfile
	elif [[ "$result" == "$(cat $tempfile)" ]]; then
		printf "%s Hasn\'t changed\n" "$url" 
	elif [[ "$result" != $(echo $tempfile) ]]; then
		printf "%s Has Changed\n" "$url"
		echo $result > $tempfile
	fi
	sleep 5m
done